config/routes.rb
Rails.application.routes.draw do

  mount ForestLiana::Engine => '/forest'

  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get "more_infos",               to: redirect("http://www.cforgood.com/plus-dinfos/")
  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'faq_connect',              to: 'pages#faq_connect'
  put 'newsletter',               to: 'pages#newsletter'
  get 'maintenance',              to: 'pages#maintenance'

  post 'stripe/webhook',          to: 'stripe#webhook'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:new, :create, :update] do
      get "dashboard",            to: "dashboard#dashboard"
      get "supervisor_account",   to: "dashboard#supervisor_account"
      get "profile",              to: "dashboard#profile"
      get "ambassador",           to: "dashboard#ambassador"
      get "gift",                 to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',            to: 'dashboard#dashboard'
      post 'impersonation',       to: 'dashboard#set_impersonation'
      post 'reset_impersonation', to: 'dashboard#reset_impersonation'
      get "profile",              to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  # namespace :asso do
  resources :causes, only: [:new, :create, :index, :show]
  #   get 'dashboard', to: 'dashboard#dashboard'
  # end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "/", :to => 'sessions#create'
        get '/check', :to => 'sessions#show'
        delete "/logout", :to => 'sessions#destroy'
      end
      resources :users, only: [ :create, :show, :update ]
      resources :business_categories, only: [ :index ]
      resources :businesses, only: [ :index, :show ]
      resources :perks, only: [ :show ]
      resources :uses, only: [ :create, :update ]
      resources :cause_categories, only: [ :index ]
      resources :causes, only: [ :index, :show, :create ]
      resources :contacts, only: [ :create ]
      resources :partners, only: [ :index ]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/api/v1/businesses_controller.rb
class Api::V1::BusinessesController < Api::V1::BaseController

  before_action :set_business, only: [ :show ]

  def index
    @lat_lng = set_coordinates(params[:lat], params[:lng])
    if params[:online].present? && params[:online] == "true"
      @businesses = Business.not_supervisor.includes(:perks, :business_category, :labels, :label_categories, :addresses).active.with_perks_in_time.distinct.merge(Address.near(@lat_lng, 99999, order: "distance"))
    else
      @businesses = Business.not_supervisor.includes(:perks, :business_category, :labels, :label_categories, :addresses).active.for_map.with_perks_in_time.distinct.merge(Address.near(@lat_lng, 99999, order: "distance"))
    end
    authorize @businesses
    # event for no business around
    current_user.create_event_no_business(@lat_lng) if @businesses.merge(Address.near(@lat_lng, 50)).size == 0
    # event for ecosystem change
    ecosystem_now = Ecosystem.within(@lat_lng).first.try(:name) if is_number?(params[:lat]) && is_number?(params[:lng])
    current_user.create_event_last_ecosystem_seen(ecosystem_now) if ecosystem_now.present? && ecosystem_now != current_user.last_ecosystem_seen
  end

  def show
    @address = Address.includes(:timetables).find(params[:address_id])
  end

  private

  def set_business
    @business = Business.includes(:label_categories, :perks_in_time).find(params[:id])
    authorize @business
  end
end

app/controllers/businesses/dashboard_controller.rb
class Pro::DashboardController < Pro::ProController

  def dashboard
    @business = Business.find(params[:business_id])
    @perks = @business.perks
    authorize @business

    @businesses = Business.joins(:perks).where("perks.permanent = ?", true).distinct

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@businesses) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
      if business.id == current_business.id
        marker.title "C'est vous !"
      end
      marker.picture({
                  # url: business.picture.url(:thumb),
                  width: 32,
                  height: 32
                 })
      marker.infowindow render_to_string(partial: "/businesses/map_box", locals: { business: business })
    end
  end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :get_coordinates, only: [:index, :show]
  before_action :find_businesses_for_search, only: [:index, :show]

  def index
    @addresses_id = []
    @businesses.each do |business|
      business.addresses.shop.each do |address_shop|
        @addresses_id << [business.id, address_shop.id]
      end
      if business.itinerant
        business.addresses.today.each do |address_itinerant|
           @addresses_id << [business.id, address_itinerant.id]
        end
      end
    end
    @addresses_id.delete([]) # REMOVE WHEN NO ACTIVE RECORD ASSOCIATION
  end

  def businesses_index
    @businesses = Business.all
  end

  def show
    # save request.referer when logout access
    if !user_signed_in?
      session[:referer] = request.url
    else
      session.delete(:referer)
    end
    @business = Business.includes(:business_category).joins(:perks).find(params[:id])
    @perks = @business.perks.includes(:perk_detail).active
    @address = @business.addresses.includes(:timetables).find(params[:address_id])
    @labels = @business.labels.includes(:label_category)

    @geojson = {"type" => "FeatureCollection", "features" => []}

    @geojson["features"] << {
      "type": 'Feature',
      "geometry": {
        "type": 'Point',
        "coordinates": [@address.longitude, @address.latitude],
      },
      "properties": {
        "marker-symbol": @business.business_category.marker_symbol,
        "color": @business.business_category.color
      }
    }
    respond_to do |format|
      format.html
      format.json{render json: @geojson}
    end
  end

  private

  def get_coordinates
    @lat_lng = set_coordinates(params[:lat], params[:lng])
  end

  def find_businesses_for_search
    @businesses = Business.not_supervisor.includes(:business_category, :perks, :labels, :label_categories).active.with_perks_in_time.distinct.eager_load(:addresses).merge(Address.near(@lat_lng, 99999, order: "distance"))
  end
end

app/controllers/pro/businesses_controller.rb
class Pro::BusinessesController < Pro::ProController

  skip_after_action :verify_authorized

  def new
    if current_impersonation
      @error = "Vous essayez de créer un commerce, nous vous avons déconnecté de #{current_impersonation.name}"
    end
    session[:impersonate_id] = nil
    @business = Business.new
  end

  def create
    @business = current_business.businesses.build(business_params)
    @business.password = 'cforgood'
    if @business.save
      session[:impersonate_id] = @business.id
      redirect_to pro_business_profile_path(current_business)
    else
      @error = "Echec de la création du commerce"
      render :new
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :email, :city, :zipcode, :business_category_id)
  end
end

app/views/businesses/_business_card.html.erb
<div class="perk-carddd <%= index_view == true || ( perk.perk_in_time? && ( !user_signed_in? || ( user_signed_in? && perk.perk_usable?(current_user) ) ) )  ? 'available' : 'unavailable' %>" id="perk-modal-dynamic-<%= perk.id %>">
    <div class="card-perks">

        <div class="background-image-perk card-img-top img-responsive" style="background-image: url('<%= perk.picture.present? ? perk.picture.url(:card) : business.picture.url(:card) %>');" alt="perk picture">
          <div class="filterrr">
           <div class="overlay-unavailable <%= index_view == true || ( perk.perk_in_time? && ( !user_signed_in? || ( user_signed_in? && perk.perk_usable?(current_user) ) ) ) ? 'hidden' : '' %>">Bon plan épuisé</div>
            <div class="card-perk-flash">
                <% if perk.flash %>
                  <div class="bolt-icon">
                      <i class="fa fa-bolt" aria-hidden="true"></i>
                  </div>
                  <% if perk.times > 0 %>
                    <p class="perks-number"><%= perk.times - Use.where(perk_id: perk.id).count %>
                      restants</p>
                  <% end %>
                <% end %>
            </div>
            <% if index_view == true %>
              <div class="business-name-card-mobile-list">
                <h6 class="business-name"> <%= business.name.downcase.titleize %> </h6>
                <% if device_type != :mobile %>
                  <p class="business-activity"><%= business.activity %></p>
                <% end %>
              </div>
            <% end %>
            <div class="perks-offer-type" style="border-color: <%= business.business_category.color %>;">
                <span><%= perk.offer_type %></span>
            </div>
          </div>
        </div>
        <div class="card-perk-description">
            <p class="perk-description"><%= perk.name.downcase.capitalize %></p>
        </div>
        <% business.labels.includes(:label_category).each do |label| %>
          <% if label.label_category.name == "Monnaie Locale" %>
            <div class="label-category hidden"><%= label.label_category.name %></div>
          <% end %>
        <% end %>
    </div>
</div>

app/views/businesses/_business_perk_not_member.html.erb
<div class="perk-modal-not_member pmdjs perk-modal-dynamic-<%= perk.id %> hidden">
  <div class="card perk-modalll">
    <button type="button" class="perk-modal-close close-button">&times;</button>

    <div class="perk-modal-header">
      <div class="perk-modal-icon"></div>
      <div class="perk-modal-header-text">Espace réservé aux abonnés</div>
    </div>

    <div class="perk-modal-content">
      <h6 class="perk-modal-content-text">Rejoignez la révolution positive</h6>
      <p>Je trouve de nouveaux commerçants responsables, des associations engagées et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.</p>
    </div>

    <% if !user_signed_in? %>
      <div class="box-subscribe-connect">
        <div class="perk-modal-button-signup">
          <%= link_to signup_path do %>
            <div class="subscribe-title">S'inscrire</div>
          <% end %>
        </div>

        <div class="subtitle-or"><p> ou </p></div>

        <div class="perk-modal-button-signup dropdown">
          <div class="connect-title dropdown-toggle" data-toggle="dropdown">Se connecter</div>
          <!-- SIGNIN -->
          <div class="dropdown-menu">
            <div class="sign-box">
              <button type="button" class="perk-modal-close-signin close-button">&times;</button>
                <%= render "devise/sessions/shared/form_signin", resource: User.new, resource_name: :user%>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to "S'abonner", member_user_profile_path(current_user, anchor: 'subscription'), class: "subscribe-button" %>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>

  <script>

    $(document).ready(function() {

      $('.perk-modal-close').click(function() {
        $('.perk-modal-not_member').addClass('hidden');
      });

      $(".button-log.sign-in").click(function() {
        $('.flipper-mobile').toggleClass('flipped');
      });

      $(".close-button-signin").click(function() {
        $('.use-overlay').addClass('hidden');
        $('.flipper-mobile').toggleClass('flipped');
      });

      $(".perk-modal-close-signin").click(function() {
        $('.perk-modal-button-signup.dropdown.open').removeClass('open');
      });

    });

  </script>
<% end %>

app/views/businesses/_business_perk_show.html.erb
<div class="pmdjs perk-modal-dynamic-<%= perk.id %> hidden">

  <% perk.update_nb_view! if perk.present? && user_space? %>

  <div class="card perk-modalll">
    <div class="card-block perk-modal-top-block">
      <div class=" perk-modal-main-title">
        <h5 style="border-color: <%= business.business_category.color %>" class="card-text">Bon plan</h5>
      </div>
      <div class="perk-modal-close-button">
        <button type="button" class="closed-perk-on-modal close-button">&times;</button>
      </div>
    </div>
    <div class="background-image-perk-modal card-img-top img-responsive" style="background-image: url('<%= perk.picture.present? ? perk.picture : business.picture %>');" alt="perk picture">
    <div class="perks-offer-type-modal" style="border-color: <%= business.business_category.color %>;">
      <span><%= perk.offer_type %></span>
    </div>
  </div>
    <div class="card-block block-text-modal">

      <div class="perk-modal-perk-name">
        <%= perk.name %>
      </div>
      <div class="pmdjs-perk-description">
        <p><%= perk.description %>.</p>
      </div>

      <div class="perk-modal-alert">
        <% if perk.appel %>
        <p class="text-center">
          <i class="fa fa-bell text-center" style="background-color: <%= business.business_category.color %>;" aria-hidden="true"></i>
          Ce bon plan n'est valable qu'une seule fois.
        </p>
        <% end %>
      </div>

      <div class="perk-modal-hr"><hr></div>

      <div class="perk-modal-bottom">

        <p class="text-center perk-modal-question">Envie d'en profiter ?</p>

        <!-- FIRST PERK OFFER FOR NOT MEMBER -->
        <% if first_offer == true && !current_user.member %>
          <%= simple_form_for :use, url: perk_uses_path(perk), method: :post, remote: true, authenticity_token: true do |f| %>
            <%= f.input :perk_id, as: :hidden, input_html: {value: perk.id} %>
            <%= f.submit "", class: "btn-create-first-use", :style => "display: none;" %>
          <% end %>

          <button class="button-validation-modal btn-first-offer" style="background-color:<%= business.business_category.color %>;">
            <p>Afficher ma carte de membre</p>
          </button>

        <!-- PERK EMAIL -->
        <% elsif perk.perk_detail.name == "email" %>
          <p class="text-center perk-modal-answer">Envoyez-nous un email pour réserver votre bon plan.</p>
          <a href='mailto:<%= business.email %>?subject=Nouvelle demande de bon plan CforGood !&body=Bonjour <%= business.leader_first_name if business.leader_first_name.present? %>,%0D%0A<%= business.name %> semble sympa comme tout !%0D%0AJe souhaiterais bénéficier du bon plan « <%= perk.name.gsub(/%/, "%25").upcase %> » (Code : <%= perk.perk_code %>), pouvez-vous me dire comment procéder ?%0D%0A Merci par avance !%0D%0A<%= current_user.first_name.capitalize if current_user.first_name.present? %> <%= current_user.last_name.capitalize if current_user.last_name.present? %>' class="button-validation-modal send-email <%= perk.id %>" style="background-color:<%= business.business_category.color %>;" target="_blank">
            Nous écrire
          </a>
          <%= simple_form_for :use, url: perk_uses_path(perk), method: :post, remote: true, authenticity_token: true do |f| %>
            <%= f.input :perk_id, as: :hidden, input_html: {value: perk.id} %>
            <%= f.submit "", class: "btn-create-use-#{perk.id}", :style => "display: none;" %>
          <% end %>

        <!-- PERK ONLINE -->
        <% elsif business.online %>
        <p class="text-center perk-modal-answer">Découvrez le code promo en cliquant ci-dessous !</p>

          <!-- <div class="perk-modal-answer">CODE PROMO : <strong><%#= perk.perk_code.upcase %></strong></div> -->

          <%#= link_to "#{business.url}", id: "popup-code-promo-#{perk.id}  ", class: "button-validation-modal send-to-code-promo #{perk.id}", style: "background-color:#{business.business_category.color};", target:"_blank" do %>
            <!-- Obtenir le code promo
          <#% end %> -->

          <button id="popup-code-promo-<%=perk.id%>" class="button-validation-modal send-to-code-promo" style="background-color:<%= business.business_category.color %>;">Obtenir le code promo</button>

          <%= render "components/popup_code_promo", business: perk.business, perk: perk %>


        <!-- PERK MEMBER CARD DESKTOP -->
        <% elsif device_type != :mobile && first_offer == false %>
          <p class="text-center perk-modal-answer">Rendez-vous en magasin avec votre smartphone</p>
          <div class="itinary-modal-section">
            <div class="itinary-modal-arrow">
              <%= link_to "http://maps.google.com/maps", class: "itinary-arrow", id: "link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: address.latitude, longitude: address.longitude } }, :target => "_blank" do %>
              <i class="fa fa-location-arrow fa-2x"></i>
              <% end %>
            </div>
              <p class="label-itinary">Afficher l'itinéraire</p>
          </div>

        <!-- PERK MEMBER CARD MOBILE -->
        <% else %>
          <p class="text-center perk-modal-answer">Montrez votre carte de membre au commerçant.</p>
          <div class="itinary-modal-section">
            <div class="itinary-modal-arrow">
              <%= link_to "http://maps.google.com/maps", class: "itinary-arrow", id: "link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: address.latitude, longitude: address.longitude } }, :target => "_blank" do %>
              <i class="fa fa-location-arrow fa-2x"></i>
              <% end %>
            </div>
            <p class="label-itinary">Afficher l'itinéraire</p>
          </div>
          <% if current_user.member %>
            <%= render "components/member_card", business: perk.business, perk: perk %>
          <% else %>
            <%= render "businesses/business_perk_not_member", perk: perk %>
          <% end %>
          <button class="button-validation-modal btn-show-card" id="popup-member-card-<%= perk.id %>" style="background-color:<%= business.business_category.color %>;">
            <p>Afficher ma carte de membre</p>
            <span>(Seulement chez le commerçant)</span>
          </button>
        <% end %>

        <div class="container-feedback-<%= perk.id %> <%= first_offer == true ? 'first_offer' : '' %>"></div>
      </div>
    </div>
  </div>
</div>


<% content_for :after_js do %>
  <script>
    $(document).ready(function () {

      $('.closed-perk-on-modal').click(function () {
        $(this).closest(".pmdjs").addClass('hidden');
      });

      // $('div').not('.card-block.block-text-modal').click(function () {
      //   $(this).closest(".pmdjs").addClass('hidden');
      // });

      $('.btn-first-offer').click(function () {
        $('.btn-create-first-use').click();
      });

      $('.send-email').click(function () {
        var perkId = $(this).attr('class').split('send-email ')[1];
        $('.btn-create-use-'+perkId).click();
      });

      $('.btn-show-card').click(function () {
         var classModal = $(this).attr('id');
         $('.'+classModal).removeClass('hidden').addClass('member-card-open');
         $('.close-button').css('display', 'none');
      });

      $('.send-to-code-promo').click(function () {
         var classModal = $(this).attr('id');
         $('.'+classModal).removeClass('hidden').addClass('code-promo-open');
         $('.closed-perk-on-modal').css('display', 'none');
      });

    });
  </script>
<% end %>

app/views/businesses/_business_search_index.html.erb
<div class="business-search-index-js hidden">

  <div class="text-count-container">
    <div class="text-count"></div>
  </div>

  <div class="bsmd-container">
    <div id="business-search-modal">
      <ul class="list">
        <% @businesses.each do |business| %>
          <%= link_to business_path(business, address_id: business.main_address.id) do %>
            <div class="business-index-card" style="border-bottom-color: <%= business.business_category.color %>;">
              <div class="bic-left">
                <div class="bic-photo" style="background-image: url('<%= business.picture %>');"></div>
              </div>
              <div class="bic-middle">
                <div class="bic-middle-top">
                  <div class="pastille" style="background-color:<%= business.business_category.color %>;"></div>
                  <div class="business-category-name"><%= business.business_category.name %></div>
                </div>
                <div class="bic-middle-center">
                  <div class="business-name"><%= business.name.titleize %></div>
                  <div class="business-activity"><%= business.activity %></div>
                </div>
                <div class="bic-middle-bottom">
                  <span>
                    <i style="color:<%= business.business_category.color %>;" class="fa fa-map-marker fa-2x" aria-hidden="true"></i>
                    à <%= display_distance(business.main_address.distance_from(@lat_lng)) %>
                  </span>
                </div>
                <% business.labels.includes(:label_category).each do |label| %>
                  <% if label.label_category.name == "Monnaie Locale" %>
                    <div class="label-category hidden"><%= label.label_category.name %></div>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/businesses/_modal_code_perk.html.erb
<%= simple_form_for :code, url: perk_uses_path(params[:perk_id]), remote: true, authenticity_token: true, html: { id: :create_use } do |f| %>
        <%= f.input :perk_code, input_html: { :size => 5, :maxlength => 5, id: :perk_code }  %>
        <%= f.submit "Validez", class: "button button-turquoise" %>
<% end %>
<p id="error-modal"></p>


<%#= link_to "Validez", perk_uses_path(params[:perk_id]), method: :post, target: "_blank", class: "button button-turquoise perk-code" %>

<% content_for :after_js do %>

  <script>
    $(document).ready(function() {
      $(".button-turquoise").on('click', function(e) {
        e.preventDefault();
        if ("<%= Perk.find(params[:perk_id]).perk_code %>" == $("#perk_code").val().toUpperCase()) {
          $("#create_use").submit();
        } else {
          $("#error-modal").append("Le code est erroné");
        };
      });
    });
  </script>

<% end %>

app/views/businesses/_perk_show.html.erb
<div class="pmdjs perk-modal-dynamic-<%= perk.id %> hidden">

  <% @perk.update_nb_view! if @perk.present? && user_space? %>

  <div class="pmdjs-header">
    <div class="pmdjs-title-underline" style="border-color: <%= @business.business_category.color %>;">Bon plan</div>
    <button type="button" class="closed-perk-on-modal close-button">&times;</button>
  </div>

  <div class="pmdjs-photo" style="background-image: url('<%= perk.picture.present? ? perk.picture : perk.business.picture %>');">
     <div class="pcri-offer">
      <div class="pcri-offer-tooltip" style="background-color: <%= perk.business.business_category.color %>;">
        <div><%= perk.offer_type? %></div>
      </div>
      <div class="pcri-offer-flash">
        <% if perk.times > 0 %>
          <span><i class="fa fa-flash pastille" style="background-color: #3F3F3F;" aria-hidden="true"></i><%= perk.times - Use.where(perk_id: perk.id).count %> restants</span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="pmdjs-perk-name">
    <%= perk.name %>
  </div>
  <div class="pmdjs-perk-description">
    <%= perk.description %>
  </div>

  <div class="pmu-alert">
    <% if perk.appel %>
      <span><i class="fa fa-bell pastille" style="background-color: <%= @business.business_category.color %>;" aria-hidden="true"></i>Ce bon plan n'est valable une seule fois</span>
    <% end %>
  </div>

  <div class="divider-line"></div>

  <p class="pmu-question">Envie d'en profiter ?</p>
  <% if user_signed_in? %>

    <% if perk.perk_detail.name == "email" %>
      <p class="pmu-answer">Envoyez-nous un email pour réserver votre bon plan </p>
      <a href='mailto:<%= @business.email %>?subject=Nouvelle demande de bon plan CforGood !&body=Bonjour <%= @business.leader_first_name if @business.leader_first_name.present? %>,%0D%0A<%= @business.name %> semble sympa comme tout !%0D%0AJe souhaiterais bénéficier du bon plan « <%= perk.name.gsub(/%/, "%25").upcase %> » (Code : <%= perk.perk_code %>), pouvez-vous me dire comment procéder ?%0D%0A Merci par avance !%0D%0A<%= current_user.first_name.capitalize if current_user.first_name.present? %> <%= current_user.last_name.capitalize if current_user.last_name.present? %>' class="button-validation-modal send-mail" style="background-color:<%= @business.business_category.color %>;" target="_blank">
        Nous écrire
      </a>

    <% elsif @business.online %>
      <div class="pmu-answer">CODE PROMO : <stong><%= perk.perk_code.upcase %></strong></div>
      <button class="button-validation-modal send-to-shop" style="background-color:<%= @business.business_category.color %>;">
        <%= link_to "#{@business.url}", class: "send-to-shop", target: "_blank" do %>
          Me rendre sur le site
        <% end %>
      </button>

    <% elsif device_type != :mobile %>
      <p class="pmu-answer">Rendez-vous en magasin avec votre smartphone</p>
      <%= link_to "http://maps.google.com/maps", class: "pastille itinary", id: "link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: @business.latitude, longitude: @business.longitude } }, :target => "_blank" do %>
        <i class="fa fa-location-arrow"></i>
      <% end %>

    <% else %>
      <p class="pmu-answer">Montrez votre carte de membre au commerçant.</p>
      <%= link_to "http://maps.google.com/maps", class: "pastille itinary", id: "link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: @business.latitude, longitude: @business.longitude } }, :target => "_blank" do %>
          <i class="fa fa-location-arrow"></i>
      <% end %>
      <span class="label-itinary">Afficher l'itinéraire</span>
      <button class="button-validation-modal btn-show-card" style="background-color:<%= @business.business_category.color %>;">
        <p>Affichez ma carte pour valider</p>
        <span>(seulement chez le commerçant)</span>
      </button>
    <% end %>

    <% if current_user.member %>

      <%= render "components/member_card" %>

      <% if perk.perk_detail.name == "email" || @business.online %>
        <%= simple_form_for :use, url: perk_uses_path(params[:perk_id], online: true), method: :post, remote: true, authenticity_token: true, html: { id: :create_use } do |f| %>
          <%= f.input :perk_id, as: :hidden, input_html: {value: params[:perk_id]} %>
          <%= f.submit "", class: "btn-create-use", :style => "display: none;" %>
        <% end %>
        <div class="container-feedback"></div>
      <% end %>
    <% end %>
  <% end%>
</div>


<% content_for :after_js do %>
  <script>
    $(document).ready(function(){

      $('.closed-perk-on-modal').click(function() {
         // console.log($(this).closest(".pmdjs"));
        $(this).closest(".pmdjs").addClass('hidden');
      });

      $('.send-mail, send-to-shop').click(function() {
        $(this).closest('.btn-create-use').click();
      });

      $('.btn-show-card').click(function() {
        $('.popup-member-card').removeClass('hidden');
      });

    });
  </script>
<% end %>