config/routes.rb
Rails.application.routes.draw do

  mount ForestLiana::Engine => '/forest'

  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get "more_infos",               to: redirect("http://www.cforgood.com/plus-dinfos/")
  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'faq_connect',              to: 'pages#faq_connect'
  put 'newsletter',               to: 'pages#newsletter'
  get 'maintenance',              to: 'pages#maintenance'

  post 'stripe/webhook',          to: 'stripe#webhook'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:new, :create, :update] do
      get "dashboard",            to: "dashboard#dashboard"
      get "supervisor_account",   to: "dashboard#supervisor_account"
      get "profile",              to: "dashboard#profile"
      get "ambassador",           to: "dashboard#ambassador"
      get "gift",                 to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',            to: 'dashboard#dashboard'
      post 'impersonation',       to: 'dashboard#set_impersonation'
      post 'reset_impersonation', to: 'dashboard#reset_impersonation'
      get "profile",              to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  # namespace :asso do
  resources :causes, only: [:new, :create, :index, :show]
  #   get 'dashboard', to: 'dashboard#dashboard'
  # end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "/", :to => 'sessions#create'
        get '/check', :to => 'sessions#show'
        delete "/logout", :to => 'sessions#destroy'
      end
      resources :users, only: [ :create, :show, :update ]
      resources :business_categories, only: [ :index ]
      resources :businesses, only: [ :index, :show ]
      resources :perks, only: [ :show ]
      resources :uses, only: [ :create, :update ]
      resources :cause_categories, only: [ :index ]
      resources :causes, only: [ :index, :show, :create ]
      resources :contacts, only: [ :create ]
      resources :partners, only: [ :index ]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/layouts/shared/_footer.html.erb
<div id="footer">
  <div class="col-xs-12 col-sm-2" id="logo-footer">
    <%=image_tag("logopouce.png") %>
  </div>
  <div class="col-xs-12 col-sm-2" id="footer-menu">
    <ul>
      <li class="footer-title">CforGood</li>
      <li><%= link_to "A propos", about_path %></li>
      <li><%= link_to "Notre charte", notre_charte_path %></li>
      <li><%= link_to "Contact", new_contact_form_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <!-- <li><a href="/notre_charte"><p>Presse</p></a></li> -->
    </ul>
  </div>
  <div class="col-xs-12 col-sm-2">
    <ul>
      <li class="footer-title">Communauté</li>
      <!--<li><a href="/notre_charte"><p>Nos Partenaires</p></a></li>-->
      <li><a class="typeform-share" href="https://cforgood1.typeform.com/to/iZ5QFx" data-mode="1" target="_blank"><p>Devenir Ambassadeur</p></a></li>
      <li><%= link_to "Vous êtes une entreprise", landing_business_path %></li>
      <li><%= link_to "Vous êtes une association", landing_cause_path %></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-3">
    <ul>
      <li class="footer-title">Légal</li>
      <li><%= link_to "Conditions Générales", cgu_path %></li>
      <li><%= link_to "Charte De Confidentialité", charte_confidentialite_path %></li>
      <li><%= link_to "Mentions Légales", mentions_legales_path %></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-3">
    <div class="col-xs-12" id="newsletter-footer">
      <li class="footer-title">Newsletter</li>
        <%= simple_form_for :newsletter, url:  newsletter_path, remote: true, method: :put do |f| %>
          <%= f.input :email, :label => false, :placeholder => "Email", :as => :email %>
          <%= f.button :submit, '>', class: "button button-turquoise" %>
        <% end %>
    </div>
    <div class="col-xs-12" id="social-media">
      <li class="footer-title">Suivez-Nous</li>
        <ul class="list-inline">
            <li>
              <a href="https://www.facebook.com/cforgood?fref=ts" class="link-contrast footer-icon-container-facebook" target="_blank">
                <i class="fa fa-facebook footer-icon"></i>
              </a>
            </li>

            <li>
              <a href="https://twitter.com/CforGood" class="link-contrast footer-icon-container-twitter" target="_blank">
                <i class="fa fa-twitter footer-icon"></i>
              </a>
            </li>

            <li>
              <a href="https://instagram.com/cforgood/" class="link-contrast footer-icon-container-instagram" target="_blank">
                <i class="fa fa-instagram footer-icon"></i>
              </a>
            </li>

            <li>
              <a href="https://fr.linkedin.com/company/cforgood" class="link-contrast footer-icon-container-linkedin" target="_blank">
                <i class="fa fa-linkedin footer-icon"></i>
              </a>
            </li>

        </ul>
    </div>
    <div class="row-space-top-2 col-xs-12">
      <h3>© CforGood 2016</h3>
    </div>
  </div>

    <div class="clear"></div>
    <div class="line-separator col-xs-12 col-sm-4 col-sm-offset-4"></div>
    <div class="clear"></div>
    <div class="text-center" id="sub-footer">
      <p>Réalisé avec <i class="fa fa-heart pl-5 pr-5"></i> à Bordeaux</p>
    </div>
    <div class="clear"></div>
</div>

app/views/layouts/shared/_head.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta name="apple-mobile-web-app-capable" content="yes">

<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- OneSignal -->

<link rel="manifest" href="/manifest.json">
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script>
  var OneSignal = OneSignal || [];
  <% if !Rails.env.development? %>
    OneSignal.push(["init", {
      appId: "<%= ENV['ONESIGNAL_APP_ID'] %>",
      safari_web_id: "<%= ENV['ONESIGNAL_SAFARI_WEB_ID'] %>",
      autoRegister: true,
      welcomeNotification: {
        "title": "CforGood",
        "message": "Merci pour votre inscription !",
        // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
      },
      notifyButton: {
        enable: false,/* Set to false to hide */
        text: {
          'tip.state.unsubscribed': 'Afficher les notifications',
          'tip.state.subscribed': 'Vous êtes abonné aux notifications',
          'tip.state.blocked': 'Vous avez bloqué les notifications',
          'message.prenotify': 'Cliquer pour accepter les notifications',
          'message.action.subscribed': 'Merci de nous suivre !',
          'message.action.resubscribed': 'Vous êtes inscrit aux notifications !',
          'message.action.unsubscribed': 'Vous ne recevrez plus de notifications',
          'dialog.main.title': 'Gérer les notifications',
          'dialog.main.button.subscribe': 'AUTORISER',
          'dialog.main.button.unsubscribe': 'BLOQUER',
          'dialog.blocked.title': 'Débloquer les notifications',
          'dialog.blocked.message': 'Suivez ces instructions pour autoriser les notifications :'
        },
      },
      promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
        /* actionMessage limited to 90 characters */
        actionMessage: "Nous aimerions vous envoyer nos dernières nouvelles et mises à jour.",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: 'AUTORISER',
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: 'NON MERCI'
      }
    }]);
  <% else %>
    OneSignal.push(["init", {
      appId: "<%= ENV['ONESIGNAL_APP_ID'] %>",
      safari_web_id: "<%= ENV['ONESIGNAL_SAFARI_WEB_ID'] %>",
      autoRegister: true,
      subdomainName: 'cforgood',
      notifyButton: {
        enable: false,/* Set to false to hide */
        text: {
          'tip.state.unsubscribed': 'Afficher les notifications',
          'tip.state.subscribed': 'Vous êtes abonné aux notifications',
          'tip.state.blocked': 'Vous avez bloqué les notifications',
          'message.prenotify': 'Cliquer pour accepter les notifications',
          'message.action.subscribed': 'Merci de nous suivre !',
          'message.action.resubscribed': 'Vous êtes inscrit aux notifications !',
          'message.action.unsubscribed': 'Vous ne recevrez plus de notifications',
          'dialog.main.title': 'Gérer les notifications',
          'dialog.main.button.subscribe': 'AUTORISER',
          'dialog.main.button.unsubscribe': 'BLOQUER',
          'dialog.blocked.title': 'Débloquer les notifications',
          'dialog.blocked.message': 'Suivez ces instructions pour autoriser les notifications :'
        },
      },
      promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
        /* actionMessage limited to 90 characters */
        actionMessage: "Nous aimerions vous envoyer nos dernières actualités.",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: 'AUTORISER',
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: 'NON MERCI'
      }
    }]);
  <% end %>
  // OneSignal.push(function() {
  // /* These examples are all valid */
  //   OneSignal.getUserId(function(userId) {
  //     console.log("OneSignal User ID:", userId);
  //     // (Output) OneSignal User ID: 270a35cd-4dda-4b3f-b04e-41d7463a2316
  //   });
  // });
</script>

<!-- Favicons -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'favicons/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'favicons/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'favicons/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'favicons/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'favicons/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'favicons/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'favicons/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'favicons/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'favicons/apple-touch-icon-180x180.png' %>">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-16x16.png' %>" sizes="16x16">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/favicon-194x194.png' %>" sizes="194x194">
<link rel="icon" type="image/png" href="<%= image_path 'favicons/android-chrome-192x192.png' %>" sizes="192x192">
<link rel="manifest" href="<%= image_path 'favicons/manifest.json' %>">
<link rel="shortcut icon" href="<%= image_path 'favicons/favicon.ico' %>">

<meta name="apple-mobile-web-app-title" content="CforGood">
<meta name="application-name" content="CforGood">
<meta name="theme-color" content="#ffffff">
<meta name="description" content="<%= meta_description %>">
<meta name="msapplication-TileColor" content="#347067">
<meta name="msapplication-TileImage" content="<%= image_path 'favicons/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= image_path 'favicons/browserconfig.xml' %>">

<!-- Google Site Verification -->
<meta name="google-site-verification" content="l0XiovQqM1xIHH0sNA31AmubNQsVh9b-XrcL8OKr5J4" />

<!-- Open Graph FB -->
<meta property="og:title" content="<%= meta_title %>">
<meta property="og:type" content="website">
<meta property="og:description" content="<%= meta_description %>">
<meta property="og:url" content="<%= request.url %>">
<meta property="og:image" content="<%= image_url(meta_image) %>"/>
<meta property="og:site_name" content="<%= meta_title %>">

<!-- Twitter card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META[:twitter_account] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META[:twitter_account] %>">
<meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="<%= meta_title %>">
<meta itemprop="description" content="<%= meta_description %>">
<meta itemprop="image" content="<%= image_url(meta_image) %>">

<!-- MailChimp -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">

<!-- Mapbox GL -->
<link href='//api.tiles.mapbox.com/mapbox-gl-js/v0.42.2/mapbox-gl.css' rel='stylesheet' />

<!-- Jquery -->
<link href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" >

<!-- AnimatedModal -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">

<!-- Select2 for dropdown -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">

<!-- Script for google analytics necessary in HEAD section -->
<%= render "layouts/shared/js/google_analytics" %>

<!-- Script for CRISP -->
<%= render "layouts/shared/js/crisp" %>

<!-- Script for AMPLITUDE -->
<%= render "layouts/shared/js/amplitude" %>

<!-- Script for BRANCH -->
<%= render "layouts/shared/js/branch" %>

<%= stylesheet_link_tag :application, media: "all" %>
<%= csrf_meta_tags %>

app/views/layouts/shared/_js.html.erb
<%= javascript_include_tag "application" %>

<!--  JQUERY & GOOGLE MAPS JS API -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
<script src="//cdn.jsdelivr.net/jquery.mixitup/latest/jquery.mixitup.min.js"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>
<%= render "layouts/shared/js/jquery_validate_fr" %>

<!-- Bootsrap -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- Wootric : survey -->
<% if user_signed_in? || business_signed_in? %>
  <%= render "layouts/shared/js/wootric" %>
<% end %>

<!-- Stripe -->
<script src="https://js.stripe.com/v3/"></script>

<!-- Mapbox GL -->
<script src='//api.tiles.mapbox.com/mapbox-gl-js/v0.42.2/mapbox-gl.js'></script>


<!-- Algolia place -->
<script src="https://cdn.jsdelivr.net/places.js/1/places.min.js"></script>

<!-- Select2 : dropdown search -->
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

<!-- Geolocalisation -->
<script>getGeolocation();</script>

<!-- JS SCRIPTS -->
<%= render "layouts/shared/js/smooth_scroll" %>
<%= render "layouts/shared/js/typeform" %>
<% if user_signed_in? || business_signed_in? %>
  <%= render "layouts/shared/js/intercom" %>
<% else %>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<div id="banner-promo">Cforgood rejoint POI, l'app qui mesure ton impact positif ! Vous aussi, inscrivez-vous à <%= link_to "l'app", "https://www.poi.app", target: "_blank"%> ou rejoignez le <%= link_to "réseau", "https://www.poi.network", target: "_blank"%> ! </div>
<div class="branch-journeys-top"></div>
<div class="navbar-v2">

  <% if user_signed_in? %>
    <%= link_to member_user_dashboard_path(current_user) do %>
      <div class="navbar-logo-item left hidden-xs"></div>
    <% end %>
  <% elsif business_signed_in? %>
    <%= link_to pro_business_dashboard_path(current_business) do %>
      <div class="navbar-logo-item left hidden-xs"></div>
    <% end %>
  <% else %>
    <%= link_to root_path do %>
      <div class="navbar-logo-item left hidden-xs"></div>
    <% end %>
  <% end %>

  <div id="open-leftmenu" class="visible-xs"><%= image_tag 'icons/menu_burger.svg' %></div>

  <!-- Impersonnate businesses -->
  <% if business_signed_in? && pro_space? && current_business.supervisor %>
    <div class="nav-impersonate">
      <%= render "components/select_impersonate_business", dropdown_search: "navbar_select_impersonate" %>
      <% if current_impersonation %>
        <div class="current-impersonation">
          Vous agissez en tant que <%= current_impersonation.name %>
          <%= link_to pro_business_reset_impersonation_path(current_business), method: :post do %>
            <button type="button" class="reset-impersonation">&times;</button>
          <% end %>
        </div>
      <% end %>
    </div>

  <% end %>

  <div class="navbar-right-item">

    <% if user_space? %>

      <div class="search-navbar search-modal-button hidden-xs">
        <i class="fa fa-search" aria-hidden="true"></i>
      </div>
      <div class="search-navbar-mobile search-modal-button-mobile">
        <i class="fa fa-search" aria-hidden="true"></i>
      </div>

      <% if current_page?('/causes') %>
        <div class="search-input-mobile hidden hidden-sm hidden-md hidden-lg">
          <input id="search-in-navbar-mobile-assos"class="search" placeholder="rechercher">
        </div>
      <% elsif current_page?('/businesses') %>
        <div class="search-input-mobile hidden hidden-sm hidden-md hidden-lg">
          <input id="search-in-navbar-mobile-perks"class="search" placeholder="rechercher">
        </div>
      <% else %>
        <div class="search-input-mobile hidden hidden-sm hidden-md hidden-lg">
          <input id="search-in-navbar-mobile"class="search" placeholder="rechercher">
        </div>
      <% end %>

      <div class="search-navbar-mobile search-modal-button-mobile business-search-close-button-mobile hidden">&times;</div>

    <% end %>

    <div class="dropdown-navbar" id="button-dropdown-navbar">

      <% if user_signed_in? %>
        <span class="hidden-xs name-navbar-user"><%= name_user(current_user) %></span>
        <div class="avatar-navbar dropdown-toggle" data-toggle="dropdown">
          <%= render partial: 'components/avatar_or_picture', locals: { resource: current_user, style: "avatar" } %>
          <div class="caret"></div>
        </div>
      <% elsif business_signed_in? %>
        <span class="hidden-xs name-navbar-business"><%= current_business.name %></span>
        <div class="avatar-navbar dropdown-toggle" data-toggle="dropdown">
          <%= render partial: 'components/avatar_or_picture', locals: { resource: current_business, style: "avatar" } %>
          <div class="caret"></div>
        </div>
      <% else %>
        <!-- SIGNUP/SIGNIN BUTTONS -->
        <div class="nav-right">
          <%= link_to signup_path, class: "sign-up" do %>
            <div class="ripple-area js-ripple">
              <span class="ripple-circle"></span>
            </div>
            S'inscrire
          <% end %>
          <%= link_to signin_path, class: "sign-in" do %>
            <div class="ripple-area js-ripple">
              <span class="ripple-circle"></span>
            </div>
            Se connecter
          <% end %>
        </div>
        <div class="navbar-logo-item visible-xs dropdown-toggle" data-toggle="dropdown">
          <div class="caret"></div>
        </div>

      <% end %>

      <ul class="dropdown-menu dropdown-menu-right">

        <div class="drop-header-container">
          <% if user_signed_in? %>
            <% if !current_user.supervisor %>
              <%= link_to "Profil", member_user_profile_path(current_user, anchor: 'profile' ), class: "droptext-bold profile-tab" %>
              <%= link_to "Association", member_user_profile_path(current_user, anchor: 'cause'), class: "droptext-bold profile-tab" %>
              <%= link_to "Participation", member_user_profile_path(current_user,  anchor: 'subscription'), class: "droptext-bold profile-tab" %>
              <% if current_user.payments.present? %>
                <%= link_to "Contributions", member_user_profile_path(current_user, anchor: 'list-payments'),  class: "droptext-bold profile-tab" %>
              <% end %>
              <%#= link_to "Plaisir d'offrir", member_user_gift_path(current_user), class: "droptext-bold profile-tab" %>
            <% end %>
          <% elsif business_signed_in? %>
            <% if !current_business.supervisor %>
              <%= link_to "Mes informations", pro_business_profile_path(current_business, anchor: 'business' ), class: "droptext-bold profile-tab" %>
              <%= link_to "Mon commerce", pro_business_profile_path(current_business, anchor: 'shop'), class: "droptext-bold profile-tab" %>
            <% end %>
          <% else %>
            <%= link_to signup_path do %>
              <div class="droptext">
                <div class="droptext-bold">S'inscrire</div>
              </div>
            <% end %>
            <%= link_to signin_path do %>
              <div class="droptext">
                <div class="droptext-bold">Se connecter</div>
              </div>
            <% end %>
          <% end %>
        </div>

        <% if user_signed_in? || business_signed_in? %>
          <li role="separator" class="divider"></li>
          <li>
            <%= link_to faq_connect_path do %>
              <div class="droptext-opacity">Aide et conseils</div>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <div class="droptext-opacity">Déconnexion</div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% if user_space? %>
  <% if current_page?('/causes') %>
    <div class="search-modal hidden">
      <input id="search-assos" class="search" placeholder="rechercher">
      <div class="close-search-modal">&times;</div>

    </div>
  <% elsif current_page?('/businesses') %>
    <div class="search-modal hidden">
      <input id="search-businesses" class="search" placeholder="rechercher">
      <div class="close-search-modal">&times;</div>

    </div>
  <% else %>
    <div class="search-modal hidden">
      <input id="search-dashboard"class="search" placeholder="rechercher">
      <div class="business-search-close-button">
        <div>Annuler</div>
      </div>
    </div>
  <% end %>
<% end %>

<% content_for :after_js do %>
  <script>

    $(document).ready(function() {
      $('.profile-tab').click(function(e) {
        var id = $(e.target).attr("href").split('#')[1];
        window.location.hash = id;
        window.location.reload();
      });
    });

  </script>
<% end %>

app/views/layouts/shared/_navbar_logout.html.erb
<nav id="nav">
  <div class="container">
    <div class="nav-items">
      <!-- LOGO LINKS -->
      <div class="nav-left">
        <!-- LOGO -->
        <%= link_to root_path do %>
          <div class="navbar-logo-item left"></div>
        <% end %>
      </div>
      <!-- SIGNUP/SIGNIN BUTTONS -->
      <div class="nav-right logout">
        <%= link_to signup_path, class: "sign-up" do %>
          <div class="ripple-area js-ripple">
            <span class="ripple-circle"></span>
          </div>
          S'inscrire
        <% end %>
        <%= link_to signin_path, class: "sign-in" do %>
          <div class="ripple-area js-ripple">
            <span class="ripple-circle"></span>
          </div>
          Se connecter
        <% end %>
      </div>
    </div>
  </div>
</nav>