config/routes.rb
Rails.application.routes.draw do

  mount ForestLiana::Engine => '/forest'

  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get "more_infos",               to: redirect("http://www.cforgood.com/plus-dinfos/")
  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'faq_connect',              to: 'pages#faq_connect'
  put 'newsletter',               to: 'pages#newsletter'
  get 'maintenance',              to: 'pages#maintenance'

  post 'stripe/webhook',          to: 'stripe#webhook'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:new, :create, :update] do
      get "dashboard",            to: "dashboard#dashboard"
      get "supervisor_account",   to: "dashboard#supervisor_account"
      get "profile",              to: "dashboard#profile"
      get "ambassador",           to: "dashboard#ambassador"
      get "gift",                 to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',            to: 'dashboard#dashboard'
      post 'impersonation',       to: 'dashboard#set_impersonation'
      post 'reset_impersonation', to: 'dashboard#reset_impersonation'
      get "profile",              to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  # namespace :asso do
  resources :causes, only: [:new, :create, :index, :show]
  #   get 'dashboard', to: 'dashboard#dashboard'
  # end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "/", :to => 'sessions#create'
        get '/check', :to => 'sessions#show'
        delete "/logout", :to => 'sessions#destroy'
      end
      resources :users, only: [ :create, :show, :update ]
      resources :business_categories, only: [ :index ]
      resources :businesses, only: [ :index, :show ]
      resources :perks, only: [ :show ]
      resources :uses, only: [ :create, :update ]
      resources :cause_categories, only: [ :index ]
      resources :causes, only: [ :index, :show, :create ]
      resources :contacts, only: [ :create ]
      resources :partners, only: [ :index ]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/businesses/dashboard_controller.rb
class Pro::DashboardController < Pro::ProController

  def dashboard
    @business = Business.find(params[:business_id])
    @perks = @business.perks
    authorize @business

    @businesses = Business.joins(:perks).where("perks.permanent = ?", true).distinct

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@businesses) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
      if business.id == current_business.id
        marker.title "C'est vous !"
      end
      marker.picture({
                  # url: business.picture.url(:thumb),
                  width: 32,
                  height: 32
                 })
      marker.infowindow render_to_string(partial: "/businesses/map_box", locals: { business: business })
    end
  end

end

app/controllers/member/dashboard_controller.rb
class Member::DashboardController < ApplicationController

  skip_before_action :authenticate_user!, only: [:dashboard]
  before_action :get_coordinates, only: [:dashboard, :profile, :gift, :ambassador]
  before_action :find_businesses_for_search, only: [:profile, :gift, :ambassador]

  def dashboard

    # Event intercom for last ecosystem request
    # if user_signed_in? && request.location.city.present?
    #   ecosystem_now = Ecosystem.within([request.location.latitude, request.location.longitude]).first.try(:name)
    #   current_user.create_event_last_ecosystem_seen(ecosystem_now) if ecosystem_now.present? && ecosystem_now != current_user.last_ecosystem_seen
    # end

    # save logout access
    if !user_signed_in?
      session[:logout] = true
    end
    @businesses = Business.not_supervisor.includes(:business_category, :perks_in_time, :uses, :main_address, :labels).active.for_map.with_perks_in_time.distinct.eager_load(:addresses_for_map).merge(Address.near(@lat_lng, 99999))
    @geojson = {"type" => "FeatureCollection", "features" => []}

    @businesses_around = @businesses.merge(Address.near(@lat_lng, 50)).size
    current_user.create_event_no_business(@lat_lng) if @businesses_around == 0 && user_signed_in?


    @businesses.each do |business|
      business.addresses_for_map.each do |address|
        @geojson["features"] << {
          "type": 'Feature',
          "geometry": {
            "type": 'Point',
            "coordinates": [address.longitude, address.latitude]
          },
          "properties": {
            "marker-symbol": business.business_category.marker_symbol,
            "color": business.business_category.color,
            "description": render_to_string(partial: "components/map_box", locals: { business: business, address: address, flash: false, lat_lng: @lat_lng })
          }
        }
      end
    end

    @uses_without_feedback = []

    if user_signed_in?
      @uses_without_feedback = current_user.uses.without_feedback
      @beneficiary = Beneficiary.includes(:users).find_by_email(current_user.email)
      @user_offering = @beneficiary.try(:users)

      if !current_user.uses.first.present?
        if !current_user.member
          @first_perk_offer = Business.includes(:main_address).find(ENV['BUSINESS_ID_CFORGOOD'].to_i).perks.active.first
        elsif current_user.business_supervisor_id
          @first_perk_offer = Business.includes(:main_address).find(current_user.business_supervisor_id).perks.active.first
        end
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @geojson }
    end
  end

  def supervisor_account
    @user = User.includes(users: :cause).find(params[:user_id])
    authorize @user
    @new_employee = User.new
    @used_perks = Use.used_by_users_for(@user)
    @liked_perks = Use.liked_by_users_for(@user)
    @employees_infos = @user.users.map do |employee|
      {id: employee.id, first_name: employee.first_name, last_name: employee.last_name, cause: employee.cause.name, likes_count: employee.liked_uses.count, uses_count: employee.used_uses.count}
    end
    @employes_sorted_by_uses = @employees_infos.sort_by { |infos| infos[:uses_count] }.reverse
    @data_for_chart = @user.users.joins(:cause).group('causes.name').count
  end

  def profile
    @partner = Partner.find_by_code_partner(current_user.code_partner.upcase) if current_user.code_partner.present?
    @cause = current_user.cause
    @payments = Payment.where(user_id: current_user.id).includes(:cause).order('created_at asc')
  end

  def gift
  end

  def ambassador
  end

  private

  def get_coordinates
    @lat_lng = set_coordinates(params[:lat], params[:lng])
  end

  def find_businesses_for_search
    @businesses = Business.not_supervisor.includes(:business_category, :main_address, :perks, :labels).active.with_perks_in_time.distinct
  end

end

app/controllers/pro/dashboard_controller.rb
class Pro::DashboardController < Pro::ProController

  skip_after_action :verify_authorized, only: [:set_impersonation, :reset_impersonation]
  before_action :find_business, only: [:dashboard, :profile]

  def set_impersonation
    if current_business.supervising?(params[:impersonate_id])
      session[:impersonate_id] = params[:impersonate_id]
    else
      session[:impersonate_id] = nil
    end
    redirect_to pro_business_dashboard_path(current_business)
  end

  def reset_impersonation
    session[:impersonate_id] = nil
    redirect_to pro_business_dashboard_path(current_business)
  end

  def dashboard
    @perks = @business.perks
    authorize @business
  end

  def profile
    authorize @business
  end

  def supervisor_dashboard
    @business = current_business
    @main_address = @business.main_address
    # A modifier !!!
    # @perks = @business.businesses_perks
    authorize @business

    @geojson = {"type" => "FeatureCollection", "features" => []}

    if current_business.admin
      @businesses = Business.all.includes(:addresses, :business_category, :perks).eager_load(:businesses_perks, :businesses_perks_uses)
    else
      @businesses = @business.businesses.includes(:addresses, :business_category, :perks).eager_load(:businesses_perks, :businesses_perks_uses)
    end

    @businesses.each do |business|
      business.addresses.each do |address|
        @geojson["features"] << {
          "type": 'Feature',
          "geometry": {
            "type": 'Point',
            "coordinates": [address.longitude, address.latitude]
          },
          "properties": {
            "marker-symbol": business.business_category.marker_symbol,
            "color": business.business_category.color
          }
        }
      end
    end
  end

  private

  def find_business
    id = session[:impersonate_id] || params[:business_id]
    @business = Business.includes(:manager).find(id)
  end
end

app/views/users/dashboard/profile/_form_cause.html.erb
<!-- FORM SELECT CAUSE -->
<div class="form-edit-container">
  <div class="form-edit">
    <div class="row">
      <div class="form-card form-select-cause">
        <div class="dashboard-title">Choississez votre cause</div>
        <% Cause.all.sample(3).each do |cause| %>
          <%= link_to user_update_cause_path(cause_id: cause.id), method: :put, remote: true, authenticity_token: true do %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="row relative cause-card" >
                <div class="bg-cause-card" style="background-image: url(<%= cause.picture.url(:medium) %>)">
                  <div class="cause-popover" id="<%= cause.id %>", data-content="<%= cause.description %>" data-placement="bottom" data-original-title="<%= cause.name %>" data-trigger="hover">
                    <div class="row" id="cause-category">
                      <p><%= cause.cause_category.name %></p>
                    </div>
                    <div class="row" id="cause-info">
                      <div class="col-xs-12" id="cause-name">
                        <h1><%= cause.name.upcase %></h1>
                      </div>
                    </div>
                    <div class="row" id="cause-impact">
                      <p><%= cause.impact.upcase %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="form-list-causes">
          <p>Vous pouvez aussi sélectionner une association parmi la liste ci-dessous :</p>
          <%= simple_form_for(current_user, url: user_update_profile_path, remote: true, authenticity_token: true, html: { method: :put, id: :update_cause_id }) do |f| %>
            <%= f.input :cause_id, collection: Cause.all, label: false, prompt: ("Ou sélectionnez parmi les autres associations"), selected: current_user.cause_id %>
             <%= f.submit "Validez", class: "btn btn-turquoise" %>
          <% end %>
        </div>
        <p class="cause-alinea">Sans choix de votre part, votre abonnement sera reversé à CforGood !</p>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>

  <script>
    $(document).ready(function() {
      $(".cause-popover").on("click", function(e) {
        e.preventDefault;
        var causeId = $(this).val('div').attr('id');
        $(".cause-border-select").toggleClass("cause-border-select");
        $($(this).toggleClass("cause-border-select"));
        $("select").val(causeId);
      });

      $(".cause-popover").popover({
        html: true,
        container: "body",
        trigger: "hover"
      });
    });
  </script>

<% end %>

app/views/users/dashboard/profile/_form_payment.html.erb
<!-- FORM CARD REGISTRATION -->
<div class="form-edit-container">
  <div class="form-edit">
    <div class="row">
      <div class="dashboard-title">Renseignez vos données bancaires</div>
      <div class="col-xs-12 col-sm-8 col-sm-offset-2 form-card form-payment">
        <div class="subscription-form">
          <form id="form-card-creation">
            <div class="form-group">
              <label for="card_number" class="control-label">Numéro de carte</label>
              <input type="text" name="card_number" id="card_number" size="18" class="form-control">
            </div>
            <div class="form-group">
              <label for="card_exp_date" class="control-label">Date d'expiration</label>
              <input type="text" name="card_exp_date" id="card_exp_date" size="6" placeholder='mmaa' class="form-control">
            </div>
            <div class="form-group">
              <label for="card_cvx" class="control-label">Cryptogramme visuel</label>
              <input type="text" name="card_cvx" id="card_cvx" size="4" class="form-control">
            </div>
            <input type="submit" value="Validez"  id="create-card" class="btn btn-default btn-account">
          </form>
          <div class="hidden">
            <%= simple_form_for :card, url: accounts_path, html: { id: :create_account } do |f| %>
              <%= f.input :id, as: :hidden %>
              <%= f.submit "", :style => "display: none;" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-8 col-sm-offset-2 form-card form-payment">
        <div class="card-authorized">
          <ul>
            <li><img src="<%= image_path 'cb.jpg' %>" alt="CB"></li>
            <li><img src="<%= image_path 'visa.jpg' %>" alt="VISA"></li>
            <li><img src="<%= image_path 'mastercard2.jpg' %>" alt="MASTERCARD"></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>

  <script>
    $(document).ready(function() {

      $.validator.addMethod("datePostToday",function(value, element) {
        var today = new Date();
        var todayMonth = today.getMonth()+1;
        var todayYear = today.getFullYear().toString().substr(2,2);
        var valueMonth = value.substr(0,2);
        var valueYear = value.substr(2,2);
        return (valueYear > todayYear || (valueYear == todayYear && valueMonth >= todayMonth));
      }, "La date d'expiration ne doit pas être révolue");

      $("#form-card-creation").validate({
        lang: 'fr',
        rules: {
          card_number: {
            required: true,
            digits: true,
            minlength: 16,
            maxlength: 16,
          },
          card_exp_date: {
            required: true,
            digits: true,
            minlength: 4,
            maxlength: 4,
            datePostToday: true,
          },
          card_cvx: {
            required: true,
            digits: true,
            minlength: 3,
            maxlength: 3
          }
        }
      });

      $("#form-card-creation").on("submit", function(e) {
        e.preventDefault();
        if ($("#form-card-creation").valid()) {
          var cardPreRegistration = <%= current_user.mangopay_id ? raw(MangopayServices.new(current_user).create_mangopay_card_pre_registration.to_json) : "null"  %>;

          // Initialize with card register data prepared on the server
          mangoPay.cardRegistration.init({
            cardRegistrationURL: cardPreRegistration.CardRegistrationURL,
            preregistrationData: cardPreRegistration.PreregistrationData,
            accessKey: cardPreRegistration.AccessKey,
            Id: cardPreRegistration.Id
          });

          // Card data collected from the user
          var cardData = {
           cardNumber: $("#card_number").val(),
           cardExpirationDate: $("#card_exp_date").val(),
           cardCvx: $("#card_cvx").val(),
           cardType: "CB_VISA_MASTERCARD"
           // cardType: $("#card_type").val()
          };

          // Set MangoPay API base URL and Client ID
          mangoPay.cardRegistration.baseURL   = "<%= ENV['MANGOPAY_API_URL'] %>";
          mangoPay.cardRegistration.clientId  = "<%= ENV['MANGOPAY_CLIENT_ID'] %>";
          var validateCard = mangoPay.cardRegistration._validateCardData(cardData);

          if (validateCard) {
            // Register card
            mangoPay.cardRegistration.registerCard(
              cardData,
              function(res) {
                $("#card_id").val(res.CardId);
                $("#create_account").submit();
                alert("Vos informations bancaires ont été correctement enregistrées")
                // Success, you can use res.CardId now that points to registered card
              },
              function(res) {
                alert("Une erreur s'est produite lors de l'enregistrement de votre carte : " + res.ResultMessage)
                // Handle error, see res.ResultCode and res.ResultMessage
              }
            );
          };
        };
      });
    });
  </script>

<% end %>

app/views/users/dashboard/profile/_form_subscription.html.erb
<!-- FORM SUBSCRIPTION -->
<div class="form-edit-container">
  <div class="form-edit">
    <div class="dashboard-title">Choisissez votre abonnement</div>
    <%= simple_form_for(current_user, url: user_update_profile_path, remote: true, authenticity_token: true, html: { method: :put, id: :form_update_subscription }) do |f| %>
      <%= f.error_notification %>
      <% if current_user.trial_done %>
        <%= f.input :subscription, label: false, as: :radio_buttons, collection:
        [["5 € par mois", "M" ], ["50 € pour un an", "A" ]], checked: current_user.subscription %>
      <% else %>
        <%= f.input :subscription, label: false, as: :radio_buttons, collection:
        [["5 € par mois", "M" ], ["50 € pour un an", "A" ], ["1 mois gratuit pour découvrir CFORGOOD !", "T"]], checked: current_user.subscription %>
      <% end %>
      <div>
        <%= f.button :submit, "Souscrivez", class: "btn btn-turquoise" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/dashboard/profile/_form_user.html.erb
<div class="form-edit-container">
  <div class="form-edit">
    <%= simple_form_for(current_user, url: user_update_profile_path, remote: true, authenticity_token: true, html: { method: :put, id: :form_profile_user }) do |f| %>
      <%= f.error_notification %>
      <%= f.input :last_name, placeholder: 'Nom', required: true, autofocus: true, label: false %>
      <%= f.input :first_name, placeholder: 'Prénom', required: true, label: false %>
      <%= f.input :email, placeholder: 'Adresse email', required: true, label: false %>
      <%= image_tag current_user.picture.url(:thumb) if current_user.picture %>
      <%= f.input :picture, as: :file, hint: 'Votre photo', required: true, label: false %>
      <%= f.button :submit, "Sauvegarder", class: "btn btn-turquoise" %>
    <% end %>
  </div>
  <div>
    <%= link_to t(".change_your_password", :default => "Changez votre mot de passe ?"), new_user_password_path(current_user), class: "new-password" %>
  </div>
</div>

app/views/users/dashboard/profile/_profile.html.erb
<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <%= render "dashboard/shared/sidebar" %>
  <!-- Content - Statistics -->
  <div class="dashboard dashboard-profile">
    <!-- Nav tabs -->
    <ul id="menu" class="nav nav-tabs">
      <li role="profile" class="active">
        <%= link_to "Vos informations", "#profile", role: "tab", data_toggle: "tab" %>
      </li>
      <li role="profile">
        <%= link_to "Votre association", "#cause", role: "tab", data_toggle: "tab" %>
      </li>
      <li role="profile">
        <%= link_to "Votre abonnement", "#subscription", role: "tab", data_toggle: "tab" %>
      </li>
      <li role="profile">
        <%= link_to "Vos données bancaires", "#account", role: "tab", data_toggle: "tab" %>
      </li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="profile">
        <%= render "form_profile_user" %>
      </div>
      <div role="tabpanel" class="tab-pane" id="cause">
        <%= render "form_profile_cause" %>
      </div>
      <div role="tabpanel" class="tab-pane" id="subscription">
        <%= render "form_profile_subscription" %>
      </div>
      <div role="tabpanel" class="tab-pane" id="account">
        <%= render "form_profile_account" %>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>

  <script>

    $(document).ready(function() {
      $("#menu a").click(function (e) {
        e.preventDefault()
        $(".alert").remove();
        $(this).tab('show');
      });
    });

  </script>

<% end %>